version: '2'
services:
  mosquitto:
    image: pascaldevink/rpi-mosquitto
    container_name: moquitto
    ports:
     - "9001:9001"
     - "1883:1883"
    restart: always
  kuiper:
    image: emqx/kuiper:1.2.1-slim
    ports:
      - "127.0.0.1:9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: manager-kuiper
    hostname: manager-kuiper
    environment:
      MQTT_SOURCE__DEFAULT__SERVERS: "[tcp://moquitto:1883]"
  influxdb-ingestion:
    image: influxdb:1.8
    container_name: influxdb-ingestion
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  influxdb-analytics:
    image: influxdb:1.8
    container_name: influxdb-analytics
    ports:
      - '8088:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  influxdb-query:
    image: influxdb:1.8
    container_name: influxdb-query
    ports:
      - '8087:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb-ingestion
    environment:
      - INFLUXDB_URL=http://influxdb-ingestion:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3001'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb-ingestion
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  mysql:
    image: datajoint/mysql:5.7
    container_name: mysql57
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # - DATAJOINT_DATABASE_CONFIG_MONITOR=FALSE
    volumes:
      - ./data:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/my.cnf
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
